<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{da3e02a2-6934-4fa9-96c3-ed725abacc49}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL.sortingConveyor();

GVL.myConveyorSortingMachine();

]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>